<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="/"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="/charts/"><i class="fa fa-bar-chart-o fa-fw"></i> Charts</a>
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>