<style type="text/css">
    #sys_info {position: fixed; bottom: 0; right: 0; width: 50%; margin: 2px 2px 0 0; padding: 3px; background: #F9F9F9; border: 1px solid #B3B4BD; font: 13px verdana; z-index:9999}
    #sys_info .block { float: left; width: 110px; height: 16px; padding-left: 10px; padding-top: 1px;}
    #sys_info #more { float: right; width: 80px; height: 16px; padding-top: 1px; padding-left: 20px;}
    #sys_info #clear { float: left; width: 35px; height: 16px; padding-top: 1px;}
    #sys_info #more-data { position: absolute; bottom: 25px; right: 0px; margin: -2px -1px 0 0; width: 90%; padding: 3px; background: #F9F9F9; border: 1px solid #B3B4BD; display: none; overflow: scroll; max-height: 300px; overflow-x: hidden;}
    #sys_info #more-data h5 { padding: 0; margin: 0 0 5px 0; font: 11px verdana; color: #A70000; font-weight: bold;}
    #sys_info a { color: #A70000; text-decoration: none; font-weight: bold; }
    #sys_info a:hover { text-decoration: underline; }
    
    #sys_info table { font: 12px verdana; border-top: 1px solid #B3B4BD; border-left: 1px solid #B3B4BD; border-right: 1px solid #B3B4BD; }
    #sys_info td { border-bottom: 1px solid #B3B4BD; padding: 3px 5px; }
    #sys_info td b { color: #0058EE; }
    #sys_info td.right { width: 60%; border-left: 1px solid #B3B4BD; color: #F88711; }
    #sys_info #thead td { background: #DDDDDD; font-weight: bold; color: #000000; }
</style>

<script type="text/javascript">
function more()
{
    if(document.getElementById('more-data').style.display == 'block') {
        document.getElementById('more-data').style.display = 'none';
    } else {
        document.getElementById('more-data').style.display = 'block';
    }
}
</script>

<div id="sys_info">
    <div class="block">
        <?php echo round($systemTime, 5); ?> ms
    </div>
    <div class="block">
        <?php echo $systemMemory; ?>
    </div>
    <div id="more">
         <a href="#" onclick="more(); return false;">SQL: &darr;&darr;&darr;</a>
    </div>
    <div id="more-data">
        <h5>DB Query</h5>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr id="thead">
                <td>Query <?php echo count($queryLog);?></td>
                <!--<td class="right">Value</td>-->
            </tr>
            <?php foreach($queryLog as $query) { ?>
                <tr class="tr">
                    <td><b><?php echo $query; ?></b></td>
                    <!--<td class="right"><?php //echo $val; ?></td>-->
                </tr>
            <?php } ?>        
        </table>
    </div>
</div>